---
- name: Configure Database servers
  hosts: databases
  become: true

  tasks:
    # - name: Install postgresql-server

    # - name: Run postgresql setup command

    # - name: Start and enable postgresql service

- name: Configure pgadmin service
  hosts: webservers
  become: true

  vars:
    pgadmin_container:
      name: pgadmin
      image: docker.io/dpage/pgadmin4
      env:
        PGADMIN_DEFAULT_EMAIL: student@example.com
        PGADMIN_DEFAULT_PASSWORD: learn_ansible
      generate_systemd:
        path: /etc/systemd/system/
        container_prefix: app
        restart_policy: always
      ports:
        - 8083:80
      network: host

    pgadmin_service_name: app-pgadmin

  tasks:
    # - name: Run podman container using pgadmin_container var

    # - name: Start, enable and reload daemon for {{ pgadmin_service_name }}
