---
- name: Configure Database servers
  hosts: databases
  become: true

  tasks:
    - name: Install postgresql-server
      ansible.builtin.package:
        name: postgresql-server
        state: present

    - name: Run postgresql setup command
      ansible.builtin.command: postgresql-setup initdb
      args:
        creates: /var/lib/pgsql/data/postgresql.conf

    - name: Start and enable postgresql service
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: true

- name: Configure pgadmin service
  hosts: webservers
  become: true

  vars:
    pgadmin_container:
      name: pgadmin
      image: docker.io/dpage/pgadmin4
      env:
        PGADMIN_DEFAULT_EMAIL: student@example.com
        PGADMIN_DEFAULT_PASSWORD: learn_ansible
      generate_systemd:
        path: /etc/systemd/system/
        container_prefix: app
        restart_policy: always
      ports:
        - 8083:80
      network: host

    pgadmin_service_name: app-pgadmin

  tasks:
    - name: Run podman container using pgadmin_container var
      containers.podman.podman_container:
        name: "{{ pgadmin_container.name }}"
        image: "{{ pgadmin_container.image }}"
        env: "{{ pgadmin_container.env }}"
        ports: "{{ pgadmin_container.ports }}"
        network: "{{ pgadmin_container.network }}"
        rm: true
        state: started
        restart: true
        generate_systemd: "{{ pgadmin_container.generate_systemd }}"

    - name: Start, enable and reload daemon for {{ pgadmin_service_name }}
      ansible.builtin.systemd:
        name: "{{ pgadmin_service_name }}"
        state: started
        enabled: true
        daemon_reload: true
