---
- name: Configure Database servers
  hosts: rhel
  become: true
  gather_facts: false

  vars:
    pgadmin_container:
      name: pgadmin
      image: docker.io/dpage/pgadmin4
      state: started
      env:
        PGADMIN_DEFAULT_EMAIL: student@example.com
        PGADMIN_DEFAULT_PASSWORD: learn_ansible
      ports:
        - 8083:80

  tasks:
    - name: Install postgresql-server
      ansible.builtin.package:
        name: postgresql-server
        state: present

    # Do the initial postgresql config & start the service & allow the traffic through the firewall
    - name: Do the initial postgresql config
      ansible.builtin.command: postgresql-setup initdb
      args:
        creates: /var/lib/pgsql/data/postgresql.conf

    - name: Start the service
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: true

    - name: Allow the traffic through the firewall
      ansible.posix.firewalld:
        port: 5432/tcp
        permanent: true
        state: enabled
        immediate: true

    - name: Create podman container using pgadmin_container var
      containers.podman.podman_container:
        name: "{{ pgadmin_container.name }}"
        image: "{{ pgadmin_container.image }}"
        state: "{{ pgadmin_container.state }}"
        env: "{{ pgadmin_container.env }}"
        ports: "{{ pgadmin_container.ports }}"
        volumes:
          - /var/lib/pgsql/data:/var/lib/postgresql/data:Z
          - /etc/localtime:/etc/localtime:ro

