- name: Configure pgadmin container
  hosts: webservers
  become: true

  vars:
    pgadmin_service_name: app-pgadmin

    pgadmin_container:
      name: pgadmin
      image: docker.io/dpage/pgadmin4:7.5
      ports:
        - 8083:80
      state: started
      network: bridge
      env:
        PGADMIN_DEFAULT_EMAIL: student
        PGADMIN_DEFAULT_PASSWORD: learn_ansible
      generate_systemd:
        path: /etc/systemd/system/
        container_prefix: app
        restart_policy: always

  tasks:
    # - name: Run podman container using pgadmin_container var

    # - name: Start, enable and reload daemon for {{ pgadmin_service_name }}