- name: Configure pgadmin container
  hosts: webservers
  become: true

  vars:
    pgadmin_service_name: app-pgadmin

    pgadmin_container:
      name: pgadmin
      image: docker.io/dpage/pgadmin4:7.5
      ports:
        - 8083:80
      state: started
      network: bridge
      env:
        PGADMIN_DEFAULT_EMAIL: student
        PGADMIN_DEFAULT_PASSWORD: learn_ansible
      generate_systemd:
        path: /etc/systemd/system/
        container_prefix: app
        restart_policy: always

  tasks:
    - name: Run podman container using pgadmin_container var
      containers.podman.podman_container:
        name: "{{ pgadmin_container.name }}"
        image: "{{ pgadmin_container.image }}"
        state: "{{ pgadmin_container.state }}"
        network: "{{ pgadmin_container.network }}"
        ports: "{{ pgadmin_container.ports }}"
        env: "{{ pgadmin_container.env }}"
        generate_systemd: "{{ pgadmin_container.generate_systemd }}"


    - name: Start, enable and reload daemon for {{ pgadmin_service_name }}
      ansible.builtin.systemd:
        name: "{{ pgadmin_service_name }}"
        state: started
        enabled: true
        daemon_reload: true